import {theme as keplerTheme} from '@kepler.gl/styles';

const blue = '#2473bd';
const blueHover = '#1869b5';
const border = '#d5dbe3';
const panel = '#f7f7f7';
const white = '#ffffff';
const text = '#29323c';
const muted = '#6a7485';

export const mapsAnalyticsTheme = {
  ...keplerTheme,
  activeColor: blue,
  activeColorHover: blueHover,
  borderColor: border,
  borderColorLT: border,
  sidePanelBg: white,
  sidePanelBorderColor: border,
  sidePanelHeaderBg: panel,
  sidePanelHeaderBorder: border,
  sideBarCloseBtnBgd: white,
  sideBarCloseBtnBgdHover: '#f0f0f0',
  sideBarCloseBtnColor: blue,
  titleTextColor: '#000000',
  titleColorLT: text,
  textColor: '#4a5568',
  textColorHl: blue,
  textColorLT: text,
  subtextColor: muted,
  subtextColorActive: blue,
  subtextColorLT: muted,
  labelColor: blue,
  labelColorLT: muted,
  labelHoverColor: blueHover,
  tooltipBg: blueHover,
  tooltipBgLT: blueHover,
  tooltipColor: white,
  tooltipColorLT: white,
  dropdownListBgd: white,
  dropdownListBgdLT: white,
  dropdownListBorderTop: border,
  dropdownListBorderTopLT: border,
  dropdownListHighlightBg: '#f0f0f0',
  dropdownListHighlightBgLT: '#f0f0f0',
  inputBgd: panel,
  inputBgdHover: white,
  inputBgdActive: white,
  inputBgdActiveLT: white,
  inputBorderColor: border,
  inputBorderHoverColor: blue,
  inputBorderActiveColor: blue,
  inputColor: text,
  inputPlaceholderColor: muted,
  inputPlaceholderColorLT: muted,
  secondaryInputBgd: panel,
  secondaryInputBgdActive: white,
  secondaryInputBgdHover: white,
  secondaryInputBorderColor: border,
  secondaryInputBorderActiveColor: blue,
  secondaryInputColor: text,
  panelBackground: panel,
  panelBackgroundLT: white,
  panelBackgroundHover: white,
  panelActiveBg: panel,
  panelContentBackground: white,
  panelBorder: border,
  panelBorderColor: border,
  panelBorderLT: `1px solid ${border}`,
  panelBoxShadow: '0 6px 12px 0 rgba(31, 41, 55, 0.12)',
  panelHeaderIcon: muted,
  panelHeaderIconActive: blue,
  panelHeaderIconHover: blueHover,
  mapPanelBackgroundColor: white,
  mapPanelHeaderBackgroundColor: panel,
  primaryBtnBgd: blue,
  primaryBtnBgdHover: blueHover,
  primaryBtnActBgd: blueHover,
  primaryBtnActColor: white,
  primaryBtnColor: white,
  primaryBtnBorder: '0',
  ctaBtnBgd: blue,
  ctaBtnBgdHover: blueHover,
  ctaBtnActBgd: blueHover,
  ctaBtnActColor: white,
  ctaBtnColor: white,
  secondaryBtnBgd: white,
  secondaryBtnBgdHover: '#f0f0f0',
  secondaryBtnActBgd: '#e6eef7',
  secondaryBtnActColor: blue,
  secondaryBtnColor: blue,
  secondaryBtnBorder: `1px solid ${border}`,
  floatingBtnBgd: white,
  floatingBtnBgdHover: '#f0f0f0',
  floatingBtnActBgd: '#e6eef7',
  floatingBtnActColor: blue,
  floatingBtnColor: '#4a5568',
  floatingBtnBorder: `1px solid ${border}`,
  floatingBtnBorderHover: `1px solid ${blue}`,
  floatingBtnRadius: '2px',
  linkBtnBgd: 'transparent',
  linkBtnBgdHover: 'transparent',
  linkBtnActBgdHover: 'transparent',
  linkBtnColor: blue,
  linkBtnActColor: blueHover,
  linkBtnBorder: '0',
  selectionBtnBgd: white,
  selectionBtnBgdHover: '#e6eef7',
  selectionBtnActBgd: '#e6eef7',
  selectionBtnColor: '#4a5568',
  selectionBtnActColor: blue,
  selectionBtnBorderColor: border,
  selectionBtnBorderActColor: blue,
  selectBackground: white,
  selectBackgroundHover: panel,
  selectBackgroundLT: white,
  selectBackgroundHoverLT: panel,
  selectBorder: `1px solid ${border}`,
  selectBorderColor: border,
  selectBorderColorLT: border,
  selectActiveBorderColor: blue,
  selectColor: text,
  selectColorLT: text,
  selectColorPlaceHolder: muted,
  selectColorPlaceHolderLT: muted,
  modalDialogBgd: white,
  modalDialogColor: text,
  modalDropdownBackground: white,
  modalFooterBgd: panel,
  modalImagePlaceHolder: '#f0f0f0',
  modalTitleColor: text,
  negativeBtnBgd: '#d64545',
  negativeBtnBgdHover: '#c23535',
  negativeBtnActBgd: '#c23535',
  progressBarColor: blue,
  progressBarTrackColor: '#e6eef7',
  errorColor: '#d64545',
  logoColor: blue
};

export default mapsAnalyticsTheme;
